name: Build and deploy to GitHub Pages
on:
 push:
  branches: ['main', 'workflow_deploy0']
jobs:
 build:
  name:build the application
  runs-on: ubuntu-latest
  steps:
  -name: Checkout
   uses:actions/checkout@v4
   -name: Install NodeJS
    uses:actions/setup-node@v4
    with:
      node-version: '20.x'
    -name: Build Angular application
    run: npm run buildci
    -name: :Archive build
    if: success()
    uses: actions/upload-artifact@v4
    with:name:deploy_dist
    path: dist
  deploy:
   name;deploy to gh-pages branch
   runs-on:ubuntu-latest
   needs; build
   steps:
  -name: Checkout
   uses:actions/checkout@v4
   -name:Download build 
   uses: actions/download-artifact@v4
   with:
    name:deploy_dist
    path: deploy_dist
  -name: Deploy to Github Pages
   uses: jamesives/github-pages-deploy-action@releases/v3
   with
  :
  GITHUB_TOKEN : ${{secrets.GITHUB_TOKEN}}
  BRANCH:gh-pages
  FOLDER:deploy-dist